# Generated by Django 5.1.3 on 2025-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0002_inventoryitem_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='added_at',
            field=models.DateField(auto_now=True),
        ),
    ]
