# Generated by Django 5.1.3 on 2025-01-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'supplier contact', 'verbose_name_plural': 'supplier contact'},
        ),
    ]
